In [1]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles/folders Python can see:")
print(os.listdir())

Current folder:
c:\Users\nagam\OneDrive\Desktop\Retail_Expansion_Intelligence\retail_analysis.ipynb

Files/folders Python can see:
['retail_analysis.ipynb']

In [2]:
import pandas as pd

train = pd.read_csv(
    r"C:\Users\nagam\OneDrive\Desktop\Retail_Expansion_Intelligence\Data\train.csv"
)

store = pd.read_csv(
    r"C:\Users\nagam\OneDrive\Desktop\Retail_Expansion_Intelligence\Data\store.csv"
)

print("Train:", train.shape)
print("Store:", store.shape)

Train: (1017209, 9)
Store: (1115, 10)

C:\Users\nagam\AppData\Local\Temp\ipykernel_34764\967481682.py:3: DtypeWarning: Columns (0: StateHoliday) have mixed types. Specify dtype option on import or set low_memory=False.
  train = pd.read_csv(

In [3]:
train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [4]:
store.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [5]:
store.info()

<class 'pandas.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Store                      1115 non-null   int64
 1   StoreType                  1115 non-null   str
 2   Assortment                 1115 non-null   str
 3   CompetitionDistance        1112 non-null   float64
 4   CompetitionOpenSinceMonth  761 non-null    float64
 5   CompetitionOpenSinceYear   761 non-null    float64
 6   Promo2                     1115 non-null   int64
 7   Promo2SinceWeek            571 non-null    float64
 8   Promo2SinceYear            571 non-null    float64
 9   PromoInterval              571 non-null    str
dtypes: float64(5), int64(2), str(3)
memory usage: 98.0 KB

In [6]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Store          1017209 non-null  int64
 1   DayOfWeek      1017209 non-null  int64
 2   Date           1017209 non-null  str
 3   Sales          1017209 non-null  int64
 4   Customers      1017209 non-null  int64
 5   Open           1017209 non-null  int64
 6   Promo          1017209 non-null  int64
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64
dtypes: int64(7), object(1), str(1)
memory usage: 79.5+ MB

In [7]:
print("TRAIN COLUMNS:")
print(train.columns.tolist())

print("\nSTORE COLUMNS:")
print(store.columns.tolist())

TRAIN COLUMNS:
['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday']

STORE COLUMNS:
['Store', 'StoreType', 'Assortment', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval']

In [8]:
train.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [9]:
store.isnull().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [10]:
train.shape

(1017209, 9)

In [11]:
store.shape

(1115, 10)

In [12]:
store["Promo2"].value_counts()

Promo2
1    571
0    544
Name: count, dtype: int64

In [13]:
store[store["Promo2"] == 0][["Promo2", "Promo2SinceWeek", "Promo2SinceYear", "PromoInterval"]].head(10)

    Promo2  Promo2SinceWeek  Promo2SinceYear PromoInterval
0        0              NaN              NaN           NaN
3        0              NaN              NaN           NaN
4        0              NaN              NaN           NaN
5        0              NaN              NaN           NaN
6        0              NaN              NaN           NaN
7        0              NaN              NaN           NaN
8        0              NaN              NaN           NaN
9        0              NaN              NaN           NaN
15       0              NaN              NaN           NaN
22       0              NaN              NaN           NaN

In [14]:
store[store["Promo2"] == 0].shape[0]

544

In [15]:
store[store["Promo2"]==1].shape[0]

571

In [19]:
store[store["CompetitionOpenSinceMonth"].isnull()]

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
11,12,a,c,1070.0,NaN,NaN,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
12,13,d,a,310.0,NaN,NaN,1,45.0,2009.0,"Feb,May,Aug,Nov"
15,16,a,c,3270.0,NaN,NaN,0,NaN,NaN,NaN
18,19,a,c,3240.0,NaN,NaN,1,22.0,2011.0,"Mar,Jun,Sept,Dec"
21,22,a,a,1040.0,NaN,NaN,1,22.0,2012.0,"Jan,Apr,Jul,Oct"
...,...,...,...,...,...,...,...,...,...,...
1095,1096,a,c,1130.0,NaN,NaN,1,10.0,2014.0,"Mar,Jun,Sept,Dec"
1099,1100,a,a,540.0,NaN,NaN,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
1112,1113,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1113,1114,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1114,1115,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"